#!/usr/bin/env node
/**
 * Demo on Sepolia with MetaMask test accounts and play money (DemoUSDC).
 *
 *   npm run demo:sepolia -- wallet                        create the deploy wallet (kept in .demo-wallets.json, gitignored)
 *   npm run demo:sepolia -- status [0xYourAddress …]      show Sepolia ETH balances
 *   npm run demo:sepolia -- deploy 0xFarmer [0xInvestor] [--resume]
 *        deploy the demo; the addresses are MetaMask test accounts that get play money (one can do both).
 *        --resume continues a deployment that stopped part-way, with the same addresses.
 *        The verifier and admin is always the AgriBridge Safe (VERIFIER_ADDRESS, default below).
 *        Writes .env.local so `npm run dev` uses this deployment, and prints the same settings for Vercel.
 *   npm run demo:sepolia -- env                           print the app settings again
 *
 * The deploy wallet is a separate throwaway key, so nobody has to export a MetaMask key: just
 * send it Sepolia ETH. It hands every role to the Safe at the end of the deployment.
 * Optional: DEPLOYER_PRIVATE_KEY (use your own funded key instead), SEPOLIA_URL (RPC used to
 * deploy), APP_RPC_URL (RPC the app reads through; defaults to a public one). See DEMO.md.
 */
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createPublicClient, formatEther, getAddress, http, isAddress, parseAbi } from "viem";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { sepolia } from "viem/chains";

import { foundryTool } from "./foundry-tools.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const WALLETS_FILE = join(root, ".demo-wallets.json");
const ENV_FILE = join(root, ".env.local");
const ENV_MARKER = "# Generated by `npm run demo:sepolia -- deploy`. Safe to delete.";
const BROADCAST_FILE = join(root, "broadcast", "DeployDemo.s.sol", String(sepolia.id), "run-latest.json");
const PUBLIC_RPC = "https://ethereum-sepolia-rpc.publicnode.com";
// The AgriBridge verifier Safe: the only verifier, and the admin of every demo contract.
const DEFAULT_VERIFIER_SAFE = "0xDa152AfD8C2efDA383fde6F840f590C93738de12";

// Wallets whose keys were published in this repo's git history. Never deploy with them.
const LEAKED = new Set([
  "0xb7d98ba6c40afb154ba36d014a2c0658ecbe4f99",
  "0xc54dc06a05f70891332940aa877ce0422266191f",
]);

/** Reads KEY=value lines from .env without overriding the real environment. */
function loadDotEnv() {
  const file = join(root, ".env");
  if (!existsSync(file)) return;
  for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (match && process.env[match[1]] === undefined) process.env[match[1]] = match[2].replace(/^["']|["']$/g, "");
  }
}

function fail(message) {
  console.error(`\n✖ ${message}\n`);
  process.exit(1);
}

const rpcUrl = () => process.env.SEPOLIA_URL || PUBLIC_RPC;
const verifierSafe = () => getAddress(process.env.VERIFIER_ADDRESS || DEFAULT_VERIFIER_SAFE);
const publicClient = () => createPublicClient({ chain: sepolia, transport: http(rpcUrl()) });

function readState() {
  return existsSync(WALLETS_FILE) ? JSON.parse(readFileSync(WALLETS_FILE, "utf8")) : {};
}

function writeState(state) {
  writeFileSync(WALLETS_FILE, `${JSON.stringify(state, null, 2)}\n`);
}

/** The deploy wallet: DEPLOYER_PRIVATE_KEY if set, otherwise the one `wallet` created. */
function deployerAccount() {
  const key = process.env.DEPLOYER_PRIVATE_KEY || readState().deployer?.privateKey;
  if (!key) fail("No deploy wallet yet. Run: npm run demo:sepolia -- wallet");
  const account = privateKeyToAccount(key.startsWith("0x") ? key : `0x${key}`);
  if (LEAKED.has(account.address.toLowerCase())) {
    fail(`${account.address} is one of the keys leaked in this repo's git history. Use a new wallet.`);
  }
  return account;
}

/**
 * Refuses a Safe that lists a leaked key among its owners: anyone holding that key could co-sign
 * as the verifier. Swap the owner in Safe{Wallet} (Settings → Owners) first.
 */
async function checkSafeOwners(safe) {
  const owners = await publicClient().readContract({
    address: safe,
    abi: parseAbi(["function getOwners() view returns (address[])"]),
    functionName: "getOwners",
  });
  const leaked = owners.filter((owner) => LEAKED.has(owner.toLowerCase()));
  if (leaked.length > 0) {
    fail(
      `The verifier Safe ${safe} lists ${leaked.join(", ")} as an owner, and that key is public in this ` +
        "repo's history. Replace that owner in Safe{Wallet} (Settings → Owners), then deploy again.",
    );
  }
}

function parseAddresses(args) {
  return args.map((arg) => {
    if (!isAddress(arg)) fail(`"${arg}" is not an Ethereum address (0x followed by 40 hex characters).`);
    return getAddress(arg);
  });
}

function readDeployment() {
  if (!existsSync(BROADCAST_FILE)) fail("No Sepolia demo deployment yet. Run: npm run demo:sepolia -- deploy 0xYourAddress");
  return Object.fromEntries(
    JSON.parse(readFileSync(BROADCAST_FILE, "utf8"))
      .transactions.filter((tx) => tx.transactionType === "CREATE")
      .map((tx) => [tx.contractName, getAddress(tx.contractAddress)]),
  );
}

/** Block of the deployment's first transaction: where the app's activity feed starts reading. */
function deploymentBlock() {
  const receipts = JSON.parse(readFileSync(BROADCAST_FILE, "utf8")).receipts ?? [];
  const blocks = receipts.map((receipt) => Number(receipt.blockNumber)).filter(Number.isFinite);
  return blocks.length ? Math.min(...blocks) : undefined;
}

function appSettings() {
  const deployed = readDeployment();
  const block = deploymentBlock();
  return [
    `NEXT_PUBLIC_CHAIN_ID=${sepolia.id}`,
    `NEXT_PUBLIC_RPC_URL=${process.env.APP_RPC_URL || PUBLIC_RPC}`,
    // Free hosted plans cap log queries at a few blocks; the public endpoint can scan history.
    `NEXT_PUBLIC_LOGS_RPC_URL=${PUBLIC_RPC}`,
    ...(block !== undefined ? [`NEXT_PUBLIC_DEPLOY_BLOCK=${block}`] : []),
    `NEXT_PUBLIC_COMMODITY_CONFIG_ADDRESS=${deployed.CommodityConfig}`,
    `NEXT_PUBLIC_COMMODITY_REGISTRY_ADDRESS=${deployed.CommodityRegistry}`,
    `NEXT_PUBLIC_COMMODITY_TOKEN_ADDRESS=${deployed.CommodityToken}`,
    `NEXT_PUBLIC_COMMODITY_PRICE_ORACLE_ADDRESS=${deployed.CommodityPriceOracle}`,
    `NEXT_PUBLIC_AGRI_SHARE_TOKEN_ADDRESS=${deployed.AgriShareToken}`,
    `NEXT_PUBLIC_LENDING_POOL_ADDRESS=${deployed.LendingPool}`,
    `NEXT_PUBLIC_LIQUIDATION_KEEPER_ADDRESS=${deployed.LiquidationKeeper}`,
    `NEXT_PUBLIC_MARKETPLACE_ADDRESS=${deployed.Marketplace}`,
    `NEXT_PUBLIC_WAREHOUSE_DESK_ADDRESS=${deployed.WarehouseDesk}`,
    `NEXT_PUBLIC_USDC_ADDRESS=${deployed.DemoUSDC}`,
    `NEXT_PUBLIC_VERIFIER_SAFE=${verifierSafe()}`,
  ];
}

function printSettings() {
  console.log("\nApp settings for Vercel (Settings → Environment Variables):\n");
  for (const line of appSettings()) console.log(line);
}

/** Writes .env.local for `npm run dev`, keeping a copy of one we did not generate. */
function writeEnvLocal() {
  const previous = existsSync(ENV_FILE) ? readFileSync(ENV_FILE, "utf8") : "";
  if (previous && !previous.startsWith(ENV_MARKER)) {
    copyFileSync(ENV_FILE, `${ENV_FILE}.backup`);
    console.log("Saved your previous .env.local as .env.local.backup");
  }
  // Keep the sign-in settings (MetaMask Embedded Wallets client ID): they belong to the app, not the deployment.
  const signIn = previous.split(/\r?\n/).filter((line) => /^NEXT_PUBLIC_WEB3AUTH_[A-Z_]+=/.test(line));
  writeFileSync(ENV_FILE, `${ENV_MARKER}\n${[...appSettings(), ...signIn].join("\n")}\n`);
  console.log("Wrote .env.local: `npm run dev` now uses this Sepolia deployment.");
}

async function status(extra) {
  const client = publicClient();
  const state = readState();
  const rows = [];
  if (process.env.DEPLOYER_PRIVATE_KEY || state.deployer) rows.push(["deploy wallet", deployerAccount().address]);
  for (const [role, address] of Object.entries(state.accounts ?? {})) rows.push([role, address]);
  for (const address of extra) rows.push(["", address]);
  if (rows.length === 0) fail("Nothing to show yet. Run: npm run demo:sepolia -- wallet");
  for (const [name, address] of rows) {
    console.log(`${name.padEnd(14)} ${address}  ${formatEther(await client.getBalance({ address }))} Sepolia ETH`);
  }
}

loadDotEnv();
const [command, ...args] = process.argv.slice(2);

if (command === "wallet") {
  const state = readState();
  if (!state.deployer) {
    const privateKey = generatePrivateKey();
    state.deployer = { address: privateKeyToAccount(privateKey).address, privateKey };
    writeState(state);
    console.log(`Created a deploy wallet in ${WALLETS_FILE} (keep this file private).`);
  }
  console.log(`\nDeploy wallet: ${state.deployer.address}`);
  console.log("Send it about 0.06 Sepolia ETH (from a faucet, or from your MetaMask test account).");
  console.log("Then: npm run demo:sepolia -- deploy 0xFarmerAddress [0xInvestorAddress]");
} else if (command === "status") {
  await status(parseAddresses(args));
} else if (command === "deploy") {
  // --resume picks up a deployment that stopped part-way (for example on a dropped RPC connection).
  const resume = args.includes("--resume");
  const addresses = parseAddresses(args.filter((arg) => arg !== "--resume"));
  if (addresses.length === 0) fail("Give the farmer's MetaMask address: npm run demo:sepolia -- deploy 0xFarmer [0xInvestor]");
  const [farmer, investor = farmer] = addresses;
  const verifier = verifierSafe();
  await checkSafeOwners(verifier);
  const deployer = deployerAccount();
  const balance = await publicClient().getBalance({ address: deployer.address });
  if (balance < 30_000_000_000_000_000n) {
    fail(`The deploy wallet ${deployer.address} has ${formatEther(balance)} Sepolia ETH. Send it about 0.06 first.`);
  }

  console.log(`Deploying the demo to Sepolia from ${deployer.address} …`);
  // Sepolia now prices contract creation far above what forge simulates (measured Oct 2026: about
  // 1,542 gas per byte of code instead of 200, so DemoUSDC needs 3.44M gas where forge predicts 521k),
  // so each transaction gets ten times forge's estimate. Only the gas actually used is paid for.
  const gasMultiplier = process.env.GAS_ESTIMATE_MULTIPLIER || "1000";
  const result = spawnSync(
    foundryTool("forge"),
    [
      "script", "script/DeployDemo.s.sol:DeployDemo",
      "--rpc-url", rpcUrl(),
      "--private-key", process.env.DEPLOYER_PRIVATE_KEY || readState().deployer.privateKey,
      "--broadcast", "--slow",
      "--gas-estimate-multiplier", gasMultiplier,
      ...(resume ? ["--resume"] : []),
    ],
    {
      cwd: root,
      stdio: "inherit",
      env: { ...process.env, VERIFIER_ADDRESS: verifier, DEMO_FARMER: farmer, DEMO_INVESTOR: investor },
    },
  );
  if (result.error || result.status !== 0) fail(`Deployment failed${result.error ? `: ${result.error.message}` : "."}`);

  writeState({ ...readState(), accounts: { verifier, farmer, investor } });
  writeEnvLocal();
  printSettings();
  console.log(`\nThe Safe ${verifier} is the verifier and admin: its owners confirm every verifier action.`);
  console.log(`Farmer ${farmer} and investor ${investor} have play money; use them in MetaMask on Sepolia.`);
} else if (command === "env") {
  printSettings();
} else {
  console.log("Usage: npm run demo:sepolia -- <wallet | status | deploy 0xFarmer [0xInvestor] | env>   (see DEMO.md)");
}
