#!/usr/bin/env node
/**
 * Demo on Sepolia with MetaMask test accounts and play money (DemoUSDC).
 *
 *   npm run demo:sepolia -- wallet                        create the deploy wallet (kept in .demo-wallets.json, gitignored)
 *   npm run demo:sepolia -- status [0xYourAddress …]      show Sepolia ETH balances
 *   npm run demo:sepolia -- deploy 0xVerifier [0xFarmer] [0xInvestor]
 *        deploy the demo; the addresses are your MetaMask test accounts (one address can play every role).
 *        Writes .env.local so `npm run dev` uses this deployment, and prints the same settings for Vercel.
 *   npm run demo:sepolia -- grant 0xAddress               make another MetaMask account a verifier and give it play money
 *   npm run demo:sepolia -- env                           print the app settings again
 *
 * The deploy wallet is a separate throwaway key, so nobody has to export a MetaMask key: just
 * send it Sepolia ETH. It keeps admin rights over the demo contracts, so keep the file private.
 * Optional: DEPLOYER_PRIVATE_KEY (use your own funded key instead), SEPOLIA_URL (RPC used to
 * deploy), APP_RPC_URL (RPC the app reads through; defaults to a public one). See DEMO.md.
 */
import { spawnSync } from "node:child_process";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { createPublicClient, createWalletClient, formatEther, getAddress, http, isAddress, keccak256, toHex } from "viem";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { sepolia } from "viem/chains";

import { foundryTool } from "./foundry-tools.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const WALLETS_FILE = join(root, ".demo-wallets.json");
const ENV_FILE = join(root, ".env.local");
const ENV_MARKER = "# Generated by `npm run demo:sepolia -- deploy`. Safe to delete.";
const BROADCAST_FILE = join(root, "broadcast", "DeployDemo.s.sol", String(sepolia.id), "run-latest.json");
const PUBLIC_RPC = "https://ethereum-sepolia-rpc.publicnode.com";

// Wallets whose keys were published in this repo's git history. Never deploy with them.
const LEAKED = new Set([
  "0xb7d98ba6c40afb154ba36d014a2c0658ecbe4f99",
  "0xc54dc06a05f70891332940aa877ce0422266191f",
]);

/** Reads KEY=value lines from .env without overriding the real environment. */
function loadDotEnv() {
  const file = join(root, ".env");
  if (!existsSync(file)) return;
  for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (match && process.env[match[1]] === undefined) process.env[match[1]] = match[2].replace(/^["']|["']$/g, "");
  }
}

function fail(message) {
  console.error(`\n✖ ${message}\n`);
  process.exit(1);
}

const rpcUrl = () => process.env.SEPOLIA_URL || PUBLIC_RPC;
const publicClient = () => createPublicClient({ chain: sepolia, transport: http(rpcUrl()) });

function readState() {
  return existsSync(WALLETS_FILE) ? JSON.parse(readFileSync(WALLETS_FILE, "utf8")) : {};
}

function writeState(state) {
  writeFileSync(WALLETS_FILE, `${JSON.stringify(state, null, 2)}\n`);
}

/** The deploy wallet: DEPLOYER_PRIVATE_KEY if set, otherwise the one `wallet` created. */
function deployerAccount() {
  const key = process.env.DEPLOYER_PRIVATE_KEY || readState().deployer?.privateKey;
  if (!key) fail("No deploy wallet yet. Run: npm run demo:sepolia -- wallet");
  const account = privateKeyToAccount(key.startsWith("0x") ? key : `0x${key}`);
  if (LEAKED.has(account.address.toLowerCase())) {
    fail(`${account.address} is one of the keys leaked in this repo's git history. Use a new wallet.`);
  }
  return account;
}

function parseAddresses(args) {
  return args.map((arg) => {
    if (!isAddress(arg)) fail(`"${arg}" is not an Ethereum address (0x followed by 40 hex characters).`);
    return getAddress(arg);
  });
}

function readDeployment() {
  if (!existsSync(BROADCAST_FILE)) fail("No Sepolia demo deployment yet. Run: npm run demo:sepolia -- deploy 0xYourAddress");
  return Object.fromEntries(
    JSON.parse(readFileSync(BROADCAST_FILE, "utf8"))
      .transactions.filter((tx) => tx.transactionType === "CREATE")
      .map((tx) => [tx.contractName, getAddress(tx.contractAddress)]),
  );
}

/** Block of the deployment's first transaction: where the app's activity feed starts reading. */
function deploymentBlock() {
  const receipts = JSON.parse(readFileSync(BROADCAST_FILE, "utf8")).receipts ?? [];
  const blocks = receipts.map((receipt) => Number(receipt.blockNumber)).filter(Number.isFinite);
  return blocks.length ? Math.min(...blocks) : undefined;
}

function appSettings() {
  const deployed = readDeployment();
  const block = deploymentBlock();
  return [
    `NEXT_PUBLIC_CHAIN_ID=${sepolia.id}`,
    `NEXT_PUBLIC_RPC_URL=${process.env.APP_RPC_URL || PUBLIC_RPC}`,
    ...(block !== undefined ? [`NEXT_PUBLIC_DEPLOY_BLOCK=${block}`] : []),
    `NEXT_PUBLIC_COMMODITY_REGISTRY_ADDRESS=${deployed.CommodityRegistry}`,
    `NEXT_PUBLIC_COMMODITY_TOKEN_ADDRESS=${deployed.CommodityToken}`,
    `NEXT_PUBLIC_COMMODITY_PRICE_ORACLE_ADDRESS=${deployed.CommodityPriceOracle}`,
    `NEXT_PUBLIC_AGRI_SHARE_TOKEN_ADDRESS=${deployed.AgriShareToken}`,
    `NEXT_PUBLIC_LENDING_POOL_ADDRESS=${deployed.LendingPool}`,
    `NEXT_PUBLIC_USDC_ADDRESS=${deployed.DemoUSDC}`,
  ];
}

function printSettings() {
  console.log("\nApp settings for Vercel (Settings → Environment Variables):\n");
  for (const line of appSettings()) console.log(line);
}

/** Writes .env.local for `npm run dev`, keeping a copy of one we did not generate. */
function writeEnvLocal() {
  if (existsSync(ENV_FILE) && !readFileSync(ENV_FILE, "utf8").startsWith(ENV_MARKER)) {
    copyFileSync(ENV_FILE, `${ENV_FILE}.backup`);
    console.log("Saved your previous .env.local as .env.local.backup");
  }
  writeFileSync(ENV_FILE, `${ENV_MARKER}\n${appSettings().join("\n")}\n`);
  console.log("Wrote .env.local: `npm run dev` now uses this Sepolia deployment.");
}

async function status(extra) {
  const client = publicClient();
  const state = readState();
  const rows = [];
  if (process.env.DEPLOYER_PRIVATE_KEY || state.deployer) rows.push(["deploy wallet", deployerAccount().address]);
  for (const [role, address] of Object.entries(state.accounts ?? {})) rows.push([role, address]);
  for (const address of extra) rows.push(["", address]);
  if (rows.length === 0) fail("Nothing to show yet. Run: npm run demo:sepolia -- wallet");
  for (const [name, address] of rows) {
    console.log(`${name.padEnd(14)} ${address}  ${formatEther(await client.getBalance({ address }))} Sepolia ETH`);
  }
}

/** Gives `address` the day-to-day verifier roles and play money, from the deploy wallet. */
async function grant(address) {
  const deployed = readDeployment();
  const account = deployerAccount();
  const client = publicClient();
  const wallet = createWalletClient({ account, chain: sepolia, transport: http(rpcUrl()) });
  const abi = (name) => JSON.parse(readFileSync(join(root, "backend", "src", "abis", `${name}.json`), "utf8"));
  const role = (name) => keccak256(toHex(name));

  const roles = [
    ["verifier role", "CommodityRegistry", role("VERIFIER_ROLE")],
    ["price updater role", "CommodityPriceOracle", role("PRICE_UPDATER_ROLE")],
    ["liquidator role", "LendingPool", role("LIQUIDATOR_ROLE")],
  ];
  for (const [label, contract, roleId] of roles) {
    const has = await client.readContract({
      address: deployed[contract], abi: abi(contract), functionName: "hasRole", args: [roleId, address],
    });
    if (has) {
      console.log(`• ${label}: already held`);
      continue;
    }
    const hash = await wallet.writeContract({
      address: deployed[contract], abi: abi(contract), functionName: "grantRole", args: [roleId, address],
    });
    await client.waitForTransactionReceipt({ hash });
    console.log(`✓ ${label}`);
  }
  const hash = await wallet.writeContract({
    address: deployed.DemoUSDC, abi: abi("DemoUSDC"), functionName: "faucet", args: [address, 50_000n * 10n ** 6n],
  });
  await client.waitForTransactionReceipt({ hash });
  console.log("✓ 50,000 play-money USDC");
}

loadDotEnv();
const [command, ...args] = process.argv.slice(2);

if (command === "wallet") {
  const state = readState();
  if (!state.deployer) {
    const privateKey = generatePrivateKey();
    state.deployer = { address: privateKeyToAccount(privateKey).address, privateKey };
    writeState(state);
    console.log(`Created a deploy wallet in ${WALLETS_FILE} (keep this file private).`);
  }
  console.log(`\nDeploy wallet: ${state.deployer.address}`);
  console.log("Send it about 0.06 Sepolia ETH (from a faucet, or from your MetaMask test account).");
  console.log("Then: npm run demo:sepolia -- deploy 0xYourMetaMaskAddress");
} else if (command === "status") {
  await status(parseAddresses(args));
} else if (command === "deploy") {
  const addresses = parseAddresses(args);
  if (addresses.length === 0) fail("Give at least one MetaMask address: npm run demo:sepolia -- deploy 0xYourAddress");
  const [verifier, farmer = verifier, investor = verifier] = addresses;
  const deployer = deployerAccount();
  const balance = await publicClient().getBalance({ address: deployer.address });
  if (balance < 30_000_000_000_000_000n) {
    fail(`The deploy wallet ${deployer.address} has ${formatEther(balance)} Sepolia ETH. Send it about 0.06 first.`);
  }

  console.log(`Deploying the demo to Sepolia from ${deployer.address} …`);
  const result = spawnSync(
    foundryTool("forge"),
    [
      "script", "script/DeployDemo.s.sol:DeployDemo",
      "--rpc-url", rpcUrl(),
      "--private-key", process.env.DEPLOYER_PRIVATE_KEY || readState().deployer.privateKey,
      "--broadcast", "--slow",
    ],
    {
      cwd: root,
      stdio: "inherit",
      env: { ...process.env, DEMO_VERIFIER: verifier, DEMO_FARMER: farmer, DEMO_INVESTOR: investor },
    },
  );
  if (result.error || result.status !== 0) fail(`Deployment failed${result.error ? `: ${result.error.message}` : "."}`);

  writeState({ ...readState(), accounts: { verifier, farmer, investor } });
  writeEnvLocal();
  printSettings();
  console.log(`\nSign in with MetaMask on Sepolia as ${verifier}: it can verify, set prices and liquidate,`);
  console.log("and the sidebar's Switch links take the same wallet to the farmer and investor views.");
} else if (command === "grant") {
  const [address] = parseAddresses(args);
  if (!address) fail("Give the MetaMask address: npm run demo:sepolia -- grant 0xAddress");
  await grant(address);
} else if (command === "env") {
  printSettings();
} else {
  console.log("Usage: npm run demo:sepolia -- <wallet | status | deploy 0xAddr… | grant 0xAddr | env>   (see DEMO.md)");
}
