#!/usr/bin/env node
/**
 * Generates typed ABI modules from Foundry build artifacts.
 *
 * Both the frontend and the backend previously carried hand-written ABI
 * fragments. One of them described a CommodityVerifier contract that does not
 * exist, and the registry's own mint call had a signature the token never
 * declared. Deriving ABIs from `out/` removes that whole class of drift: if a
 * signature changes, the generated file changes with it.
 *
 * Run `forge build` first, then `npm run abis`.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'out');

/** Contracts the application talks to. */
const CONTRACTS = [
  'CommodityRegistry',
  'CommodityToken',
  'CommodityPriceOracle',
  'AgriShareToken',
  'LendingPool',
];

/** Minimal ERC-20 surface, for USDC approve/balance calls from the frontend. */
const ERC20_ABI = [
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint8' }],
  },
  {
    type: 'function',
    name: 'symbol',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'string' }],
  },
];

if (!existsSync(outDir)) {
  console.error('❌ out/ not found. Run `forge build` first.');
  process.exit(1);
}

function readAbi(name) {
  const artifact = join(outDir, `${name}.sol`, `${name}.json`);
  if (!existsSync(artifact)) {
    console.error(`❌ Missing artifact for ${name} at ${artifact}. Run \`forge build\`.`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(artifact, 'utf8')).abi;
}

const abis = Object.fromEntries(CONTRACTS.map((name) => [name, readAbi(name)]));
abis.ERC20 = ERC20_ABI;

// ─── Frontend: a TypeScript module with `as const` so viem/wagmi infer types ───
const frontendDir = join(root, 'lib', 'contracts', 'abis');
mkdirSync(frontendDir, { recursive: true });

for (const [name, abi] of Object.entries(abis)) {
  writeFileSync(
    join(frontendDir, `${name}.ts`),
    `// Generated by scripts/generate-abis.mjs from Foundry artifacts. Do not edit.\n` +
      `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`,
  );
}

writeFileSync(
  join(frontendDir, 'index.ts'),
  `// Generated by scripts/generate-abis.mjs. Do not edit.\n` +
    Object.keys(abis)
      .map((name) => `export { ${name}Abi } from './${name}';`)
      .join('\n') +
    '\n',
);

// ─── Backend: plain JSON, consumed by ethers ───
const backendDir = join(root, 'backend', 'src', 'abis');
mkdirSync(backendDir, { recursive: true });

for (const [name, abi] of Object.entries(abis)) {
  writeFileSync(join(backendDir, `${name}.json`), `${JSON.stringify(abi, null, 2)}\n`);
}

console.log(`✅ Generated ABIs for ${Object.keys(abis).length} contracts`);
console.log(`   frontend → lib/contracts/abis/`);
console.log(`   backend  → backend/src/abis/`);
